# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2900ac5703dceec7830315ecc5ebca0e4f7fca2dd75a02482ca73af57b933925cf240089a75ecc54e08cab34f1e299a64a27127ba663186b32d277704b6d2c15

test:
  secret_key_base: 75b52a2926f5704f775793d16a1b4ee0f31a868f5db3ea871135a22f123e3dc34c54ae3acd3ea6e3f701831643d8339f0717215f7bc0295f139d207cff6fa1f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
